name 'k8s_setup'
maintainer 'Nir Shah'
maintainer_email 'nir@example.com'
license 'MIT'
description 'Installs and configures Docker and Kubernetes on EC2 instances'
version '1.0.0'
chef_version '>= 16.0'
