apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
        - name: calc-container
          image: nirshah77/sqrt-app:latest
          imagePullPolicy: Always
          stdin: true
          tty: true